spring.application.name=server
spring.config.import=optional:file:.env[.properties]
server.port=8080

#database details
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#R2 details
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_ACCESS_KEY}
r2.endpoint=${R2_ENDPOINT}
r2.bucket-name=${R2_BUCKET_NAME}

#image upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
spring.servlet.multipart.resolve-lazily=true

#frotend url
store.front.url=${STORE_FRONT_URL:http://localhost:4200}

#Stripe
stripe.secretKey=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
